// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvqvoigbdqhruudmfcou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2cXZvaWdiZHFocnV1ZG1mY291Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwODY1ODMsImV4cCI6MjA2NDY2MjU4M30.xtNOODhhRmfLP5tmhdAm607hkgBEIq6wQNWWKnkWG48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);